# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Long_Teng/Long_Teng/MIPS_CPU/MIPS_CPU.srcs/sources_1/ip/InstructionMem_1/InstructionMem.xci
# IP: The module: 'InstructionMem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Long_Teng/Long_Teng/MIPS_CPU/MIPS_CPU.gen/sources_1/ip/InstructionMem_1/InstructionMem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'InstructionMem'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/Long_Teng/Long_Teng/MIPS_CPU/MIPS_CPU.srcs/sources_1/ip/InstructionMem_1/InstructionMem.xci
# IP: The module: 'InstructionMem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Long_Teng/Long_Teng/MIPS_CPU/MIPS_CPU.gen/sources_1/ip/InstructionMem_1/InstructionMem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'InstructionMem'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
